services:
  postgres:
    image: postgres:16
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todolist-dev
    ports:
      - "5433:5432" # Puerto maquina (pgadmin)local DB 5433 -> contenedor DB 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: my_go_backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: todolist-dev
    ports:
      - "8080:8080"

volumes:
  postgres_data: